obstacles:
  - enter: [1.0, 2.0, 5.0]
    size: 0.6
  - enter: [2.0, 2.0, 5.0]
    size: 0.6
  - enter: [3.0, 2.0, 5.0]
    size: 0.6
  - enter: [4.0, 2.0, 5.0]
    size: 0.6
  - enter: [5.0, 2.0, 5.0]
    size: 0.6